nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Les domaines autoris√©s
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
        '^/api/': # Pour 'jwt'
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # ex: 'http..localhost:3000' pour react
            allow_headers: ['*'] # ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH']
            max_age: 3600